#!/bin/sh

# MIT license

C_RED="\033[1;31m"
C_YELLOW="\033[1;33m"
C_CYAN="\033[1;36m"
C_WHITE="\033[1;37m"
C_GREEN="\033[1;32m"
C_RESET="$(tput sgr0)"

if [ "$1" = "--help" -o -z "$1" ]; then
    echo "Usage: $0 <DIR> [DEPTH=2]" >&2
    echo
    echo "Scan for .git dirs under DIR (up to DEPTH dirs deep) and show git status"
    exit 1
fi

if [ -z "$2" ]; then
    DEPTH=2
else
    DEPTH=$2
fi

for GIT_DIR in $(find $1 -maxdepth $DEPTH -name ".git" -type d); do
    PROJ_DIR=$(dirname $GIT_DIR)

    printf "${PROJ_DIR}: "

    REV_MASTER_LOCAL=$(git --git-dir $GIT_DIR rev-parse --verify master)
    REV_MASTER_REMOTE=$(git --git-dir $GIT_DIR rev-parse --verify origin/master)
    UNCOMMITTED=$(git --work-tree $(dirname $GIT_DIR) --git-dir $GIT_DIR diff-index --quiet HEAD --; echo $?)
    UNTRACKED=$(git --work-tree $(dirname $GIT_DIR) --git-dir $GIT_DIR ls-files --exclude-standard --others)

    STATUS_NEEDS=""
    if [ "$REV_MASTER_LOCAL" != "$REV_MASTER_REMOTE" ]; then
        STATUS_NEEDS="${STATUS_NEEDS}${C_YELLOW}Needs push${C_RESET} "
    fi
    if [ "$UNCOMMITTED" -ne 0 ]; then
        STATUS_NEEDS="${STATUS_NEEDS}${C_RED}Uncommitted changes${C_RESET} "
    fi
    if [ "$UNTRACKED" != "" ]; then
        STATUS_NEEDS="${STATUS_NEEDS}${C_CYAN}Untracked files${C_RESET} "
    fi
    if [ "$STATUS_NEEDS" = "" ]; then
        STATUS_NEEDS="${STATUS_NEEDS}${C_GREEN}ok${C_RESET} "
    fi
    printf "$STATUS_NEEDS\n"
done
